before_script:
  - export IMAGE_TAG="$CI_COMMIT_SHA"

build-frontend:
  stage: build
  script:
    - cd frontend
    - npm run build

build-backend:
  stage: build
  script:
    - cd backend
    - ./gradlew buildDocker

deploy-live:
  stage: deploy
  script:
    - /srv/www/noodid/start_backend.docker.sh 
    
deploy-test:
  stage: deploy
  script:
    - /srv/www/noodid-test/start_backend.docker.sh 