before_script:
  - export IMAGE_TAG="Noodid-$CI_COMMIT_SHA"

build-frontend:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build

build-backend:
  stage: build
  script:
    - cd backend
    - chmod +x gradlew
    - ./gradlew buildDocker

deploy-live:
  artifacts:
    paths:
      - frontend/public/
  stage: deploy
  script:
    - cp -R frontend/public/. /srv/www/noodid/frontend/
    - /srv/www/noodid/start_backend.docker.sh 
    
deploy-test:
  artifacts:
    paths:
      - frontend/public/
  stage: deploy
  script:
    - cp -R frontend/public/. /srv/www/noodid-test/frontend/
    - /srv/www/noodid-test/start_backend.docker.sh 