spring:
  datasource:
    url:
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming.strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet.multipart:
    max-file-size: 100MB
    max-request-size: 100MB
logging:
  level:
    root: WARN
    ee.ut.pillime.noodid: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread][%logger{0}] %m%n"
  file: /logs/noodid.log
security:
  enable-csrf: true
  basic:
    enabled: false
server:
  contextPath: /
  port: 8080
spring.mail:
  host: 192.168.1.2
  port: 25